"""
CalculiX .inp dosya yazıcısı.

TetMesh + malzeme + sınır koşulları + yükler -> .inp
Sonra ccx.exe ile çalıştırılabilir.

Birim sistemi: SI (m, kg, s, N, Pa)
  - E, sigma_y: Pa (kullanıcı GPa girerse 1e9 ile çarpılmalı)
  - rho: kg/m³
  - kuvvet: N
  - basınç: Pa

Bu modül analiz adımları olarak STATIC, FREQUENCY, BUCKLE destekler.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Optional
import numpy as np

from .tet_mesher import TetMesh


@dataclass
class FEAMaterial:
    """Lineer elastik izotropik malzeme (SI birimleri)."""
    name: str
    youngs_modulus_pa: float   # Pa (örn: 70e9 = 70 GPa)
    poisson_ratio: float
    density_kg_m3: float
    yield_strength_pa: float = 0.0  # post-process için

    @classmethod
    def from_gpa(cls, name: str, e_gpa: float, nu: float, rho: float,
                 yield_mpa: float = 0.0) -> "FEAMaterial":
        return cls(
            name=name,
            youngs_modulus_pa=e_gpa * 1e9,
            poisson_ratio=nu,
            density_kg_m3=rho,
            yield_strength_pa=yield_mpa * 1e6,
        )


@dataclass
class FixedBC:
    """Sabit (encastre) sınır koşulu — verilen düğümlerde tüm DOF'lar sıfır."""
    node_ids: np.ndarray   # 1-indexed (CalculiX)
    name: str = "FIXED"
    dof_start: int = 1
    dof_end: int = 3       # 1-3 = ux, uy, uz (sadece 3D solid)


@dataclass
class PressureLoad:
    """Yüzey üçgenlerine uygulanan üniform basınç."""
    face_node_ids: np.ndarray  # (K, 3 veya 6) yüzey üçgenleri (1-indexed düğümler)
    pressure_pa: float          # pozitif = yüzeye doğru bastırır
    name: str = "PRESSURE"


@dataclass
class ForceLoad:
    """Düğümlere dağıtılmış konsantre kuvvet (toplam F, /N node ile bölünür)."""
    node_ids: np.ndarray   # 1-indexed
    direction: tuple       # (fx, fy, fz) birim vektör
    total_force_n: float
    name: str = "FORCE"


@dataclass
class FEACase:
    """Tam bir FEA çalışması."""
    name: str
    mesh: TetMesh
    material: FEAMaterial
    fixed_bcs: List[FixedBC] = field(default_factory=list)
    pressure_loads: List[PressureLoad] = field(default_factory=list)
    force_loads: List[ForceLoad] = field(default_factory=list)
    analysis_type: str = "STATIC"   # STATIC, FREQUENCY, BUCKLE
    num_modes: int = 10              # FREQUENCY/BUCKLE için


def write_inp(case: FEACase, output_dir: Path) -> Path:
    """Verilen case için CalculiX .inp dosyası yaz.

    Returns:
        Yazılan .inp dosyasının Path'i.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    inp_path = output_dir / f"{case.name}.inp"

    mesh = case.mesh
    mat = case.material
    elem_type = mesh.element_type  # C3D4 veya C3D10

    lines: List[str] = []
    lines.append("*HEADING")
    lines.append(f"Case: {case.name} (auto-generated by bilsem_beyin)")
    lines.append("**")

    # ─── DÜĞÜMLER ───
    lines.append("*NODE, NSET=NALL")
    # CalculiX 1-indexed; bizim points 0-indexed
    pts = mesh.points
    for i, (x, y, z) in enumerate(pts, start=1):
        lines.append(f"{i:8d}, {x: .9e}, {y: .9e}, {z: .9e}")
    lines.append("**")

    # ─── ELEMENTLER ───
    lines.append(f"*ELEMENT, TYPE={elem_type}, ELSET=EALL")
    tets = mesh.tets + 1  # 1-indexed'e çevir
    if elem_type == "C3D4":
        for i, conn in enumerate(tets, start=1):
            lines.append(f"{i:8d}, " + ", ".join(f"{n:d}" for n in conn))
    else:
        # C3D10: gmsh node ordering ile CalculiX/Abaqus aynı
        # (1-4 köşe, 5-10 kenar orta noktaları, sıralama eşleşir)
        for i, conn in enumerate(tets, start=1):
            lines.append(f"{i:8d}, " + ", ".join(f"{n:d}" for n in conn[:8]))
            lines.append("        " + ", ".join(f"{n:d}" for n in conn[8:]))
    lines.append("**")

    # ─── MALZEME ───
    lines.append(f"*MATERIAL, NAME={mat.name}")
    lines.append("*ELASTIC")
    lines.append(f"{mat.youngs_modulus_pa:.6e}, {mat.poisson_ratio:.4f}")
    lines.append("*DENSITY")
    lines.append(f"{mat.density_kg_m3:.6e}")
    lines.append("**")
    lines.append(f"*SOLID SECTION, ELSET=EALL, MATERIAL={mat.name}")
    lines.append("**")

    # ─── BC NODE SETLERİ ───
    for i, bc in enumerate(case.fixed_bcs, start=1):
        nset_name = f"{bc.name}_{i}"
        lines.append(f"*NSET, NSET={nset_name}")
        _write_id_list(lines, bc.node_ids)
        bc._nset_name = nset_name  # type: ignore
    lines.append("**")

    # ─── LOAD NODE SETLERİ (force) ───
    for i, fl in enumerate(case.force_loads, start=1):
        nset_name = f"{fl.name}_{i}"
        lines.append(f"*NSET, NSET={nset_name}")
        _write_id_list(lines, fl.node_ids)
        fl._nset_name = nset_name  # type: ignore
    lines.append("**")

    # ─── PRESSURE: yüzey üçgenlerini element + face olarak yazmamız gerek.
    # En basit & taşınabilir yol: her üçgen için 1 boyutlu *DLOAD yerine,
    # eşdeğer nodal kuvvetlere dönüştürmek. Üçgen alanı * basınç / 3 = her köşeye F.
    nodal_force_accumulator = {}  # (node_id, axis) -> force
    for pl in case.pressure_loads:
        tris = pl.face_node_ids
        if tris.shape[1] >= 3:
            # 3 köşeyi al (quadratic tri ise ilk 3 köşe)
            corners = tris[:, :3]
            for tri in corners:
                p1 = mesh.points[tri[0] - 1]
                p2 = mesh.points[tri[1] - 1]
                p3 = mesh.points[tri[2] - 1]
                v1 = p2 - p1
                v2 = p3 - p1
                normal = np.cross(v1, v2)
                area2 = np.linalg.norm(normal)
                if area2 < 1e-20:
                    continue
                area = 0.5 * area2
                n_unit = normal / area2  # outward normal yönü
                # Pressure: yüzeye doğru = -normal yönünde kuvvet
                f_total = -pl.pressure_pa * area * n_unit  # (3,) Newton
                f_per_node = f_total / 3.0
                for n in tri:
                    for axis in (0, 1, 2):
                        key = (int(n), axis + 1)  # CalculiX DOF: 1=x,2=y,3=z
                        nodal_force_accumulator[key] = (
                            nodal_force_accumulator.get(key, 0.0) + f_per_node[axis]
                        )

    # Force loads -> nodal kuvvetlere ekle
    for fl in case.force_loads:
        if len(fl.node_ids) == 0:
            continue
        f_per_node = np.array(fl.direction, dtype=np.float64)
        norm = np.linalg.norm(f_per_node)
        if norm < 1e-12:
            continue
        f_per_node = f_per_node / norm * (fl.total_force_n / len(fl.node_ids))
        for n in fl.node_ids:
            for axis in (0, 1, 2):
                key = (int(n), axis + 1)
                nodal_force_accumulator[key] = (
                    nodal_force_accumulator.get(key, 0.0) + f_per_node[axis]
                )

    # ─── ANALİZ ADIMI ───
    lines.append("*STEP")
    if case.analysis_type.upper() == "FREQUENCY":
        lines.append("*FREQUENCY")
        lines.append(f"{case.num_modes}")
    elif case.analysis_type.upper() == "BUCKLE":
        lines.append("*BUCKLE")
        lines.append(f"{case.num_modes}")
    else:
        lines.append("*STATIC")

    # BC'ler
    for bc in case.fixed_bcs:
        nset = getattr(bc, "_nset_name", bc.name)
        lines.append("*BOUNDARY")
        lines.append(f"{nset}, {bc.dof_start}, {bc.dof_end}, 0.0")

    # Konsantre yükler (tüm pressure + force toplamları)
    if nodal_force_accumulator and case.analysis_type.upper() == "STATIC":
        lines.append("*CLOAD")
        for (node_id, dof), val in sorted(nodal_force_accumulator.items()):
            if abs(val) < 1e-12:
                continue
            lines.append(f"{node_id}, {dof}, {val:.6e}")

    # Çıktı talepleri
    lines.append("*NODE FILE")
    if case.analysis_type.upper() == "STATIC":
        lines.append("U, RF")
        lines.append("*EL FILE")
        lines.append("S, E")
    else:
        lines.append("U")
    lines.append("*END STEP")

    inp_path.write_text("\n".join(lines), encoding="utf-8")
    return inp_path


def _write_id_list(lines: List[str], ids, per_line: int = 8) -> None:
    """ID listesini per_line ID/satır olarak ekle."""
    ids = np.asarray(ids).flatten().astype(np.int64)
    for i in range(0, len(ids), per_line):
        chunk = ids[i:i + per_line]
        lines.append(", ".join(f"{n:d}" for n in chunk))


# ─────────────────────────────────────────────────────────────────────────────
# Yüzey üçgeninden node ID çıkarma yardımcısı
# ─────────────────────────────────────────────────────────────────────────────

def surface_face_nodes(mesh: TetMesh, face_indices: np.ndarray) -> np.ndarray:
    """Verilen yüzey üçgen index'lerinden 1-indexed CalculiX node ID array'i (kümesi).

    Args:
        mesh: TetMesh
        face_indices: surface_tris içindeki üçgenlerin index'leri

    Returns:
        np.ndarray (M,) — benzersiz, sıralı, 1-indexed
    """
    if len(face_indices) == 0 or len(mesh.surface_tris) == 0:
        return np.array([], dtype=np.int64)
    selected = mesh.surface_tris[face_indices]  # (K, 3 veya 6)
    unique = np.unique(selected.flatten())
    return (unique + 1).astype(np.int64)
